# Generated by Django 3.2.5 on 2021-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('r', 'in_review'), ('p', 'published')], default='r', max_length=1, verbose_name='장소 상태'),
        ),
    ]
