# Generated by Django 3.2.5 on 2021-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bookmark_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='장소가 북바크 당한 숫자'),
        ),
    ]
