# Generated by Django 3.2.5 on 2021-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detail_address',
            field=models.TextField(default='1', verbose_name='주소2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(verbose_name='주소1'),
        ),
    ]
