# Generated by Django 3.2.5 on 2021-08-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_trackings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('point', models.IntegerField(default=0, verbose_name='점수')),
                ('name', models.CharField(choices=[('회원가입', 'signup'), ('제보 등록', 'add_report'), ('승인된 제보', 'selected_repport')], default='제보 등록', max_length=20, verbose_name='행동')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='actiontracking',
            name='action_point_rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='action_trackings.actionpointrule', verbose_name='규칙'),
            preserve_default=False,
        ),
    ]
