# Generated by Django 3.2.5 on 2021-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_trackings', '0004_alter_actionpointrule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpointrule',
            name='name',
            field=models.CharField(choices=[('제보 등록', 'add_report'), ('제보 삭제', 'destroy_report'), ('리뷰 생성', 'add_review'), ('리뷰 삭제', 'destroy_review'), ('신고 생성', 'add_inquiry'), ('신고 삭제', 'destroy_inquiry'), ('place 조회', 'add_viewcount')], default='제보 등록', max_length=20, verbose_name='행동'),
        ),
    ]
