# Generated by Django 3.2.5 on 2021-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='제보 내용'),
        ),
    ]
