# Generated by Django 3.2.5 on 2021-08-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='attachable_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='attachable_type',
        ),
    ]
