# Generated by Django 3.2.5 on 2021-08-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0002_auto_20210802_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='이미지 대표 이름'),
        ),
    ]
