# Generated by Django 3.2.5 on 2021-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0003_auto_20210803_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
