# Generated by Django 3.2.5 on 2021-08-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0003_auto_20210802_2302'),
        ('file_managers', '0003_auto_20210803_0109'),
    ]

    operations = [
    ]
