# Generated by Django 3.2.5 on 2021-08-02 16:09

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0003_auto_20210803_0109'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('places', '0003_place_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='file_managers.Image', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
