# Generated by Django 3.2.5 on 2021-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0003_auto_20210803_0109'),
        ('places', '0004_auto_20210803_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, to='file_managers.Image', verbose_name='images'),
        ),
    ]
