# Generated by Django 3.2.5 on 2021-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='장소의 조회수'),
        ),
    ]
