# Generated by Django 3.2.5 on 2021-08-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_tags'),
        ('places', '0005_alter_place_images'),
    ]

    operations = [
    ]
