# Generated by Django 3.2.5 on 2021-08-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
    ]
