# Generated by Django 3.2.5 on 2021-08-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_merge_0004_alter_place_tags_0005_alter_place_images'),
        ('places', '0006_place_view_count'),
    ]

    operations = [
    ]
