# Generated by Django 3.2.5 on 2021-08-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210809_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='place',
            name='detail_address',
            field=models.TextField(verbose_name='상세 주소'),
        ),
    ]
