# Generated by Django 3.2.5 on 2021-08-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_bookmark_count'),
        ('places', '0009_alter_place_detail_address'),
    ]

    operations = [
    ]
