# Generated by Django 3.2.5 on 2021-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managers', '0004_image_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='base64',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
