# Generated by Django 3.2.5 on 2021-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inquiry_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='신고 횟수'),
        ),
        migrations.AddField(
            model_name='user',
            name='report_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='제보 횟수'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='리뷰 작성 횟수'),
        ),
    ]
